//! Checks for text about to be published. A hit names its rule, never the
//! matched text, so the term itself does not spread into records or logs.
use anyhow::{bail, Context, Result};
use regex::{Regex, RegexBuilder};
use std::sync::LazyLock;

/// Private terms that must never be published: one regular expression per
/// line, matched case-insensitively. Blank lines and `#` comments are skipped.
#[derive(Clone, Debug, Default)]
pub struct DenyList(Vec<(usize, Regex)>);
impl DenyList {
    pub fn parse(text: &str) -> Result<Self> {
        let mut rules = vec![];
        for (n, line) in text.lines().enumerate() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if line.len() > 512 || rules.len() >= 1000 {
                bail!(
                    "deny list line {} is too long or the list is too large",
                    n + 1
                );
            }
            let rule = RegexBuilder::new(line)
                .case_insensitive(true)
                .size_limit(1 << 20)
                .build()
                .with_context(|| format!("deny list line {} is not a valid pattern", n + 1))?;
            rules.push((n + 1, rule));
        }
        Ok(Self(rules))
    }
    pub fn len(&self) -> usize {
        self.0.len()
    }
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}
/// AI attribution trailers: a co-author line naming a model or vendor, or a
/// "generated with/by" line naming an AI tool.
static TRAILER: LazyLock<Regex> = LazyLock::new(|| {
    RegexBuilder::new(
        r"(?m)^\W*(co-authored-by:.*\b(claude|anthropic|openai|chatgpt|gpt-?\d|codex|copilot|gemini)\b|(\p{So}\s*)?generated (with|by) .*\b(claude|chatgpt|codex|copilot|gemini|ai)\b)",
    )
    .case_insensitive(true)
    .build()
    .unwrap()
});
/// Every rule `text` breaks, in list order: `deny_list:<line>` for each
/// matching line, then `ai_trailer`. Empty when the text may be published.
pub fn scan(text: &str, deny: &DenyList) -> Vec<String> {
    let mut hits: Vec<String> = deny
        .0
        .iter()
        .filter(|(_, rule)| rule.is_match(text))
        .map(|(line, _)| format!("deny_list:{line}"))
        .collect();
    if TRAILER.is_match(text) {
        hits.push("ai_trailer".into());
    }
    hits
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn hits_name_the_rule_and_ordinary_text_passes() {
        let deny = DenyList::parse("# private names\n\nAlice Example\nproject-\\d+\n").unwrap();
        assert_eq!(deny.len(), 2);
        assert_eq!(scan("thanks, alice example", &deny), ["deny_list:3"]);
        assert_eq!(scan("see PROJECT-42", &deny), ["deny_list:4"]);
        // Every broken rule is named, so one fix round is enough.
        assert_eq!(
            scan(
                "alice example on project-7\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
                &deny
            ),
            ["deny_list:3", "deny_list:4", "ai_trailer"]
        );
        for trailer in [
            "Fix it\n\nCo-Authored-By: Claude Opus <noreply@anthropic.com>",
            "Done.\n🤖 Generated with Claude Code",
            "Generated by ChatGPT",
        ] {
            assert_eq!(scan(trailer, &deny), ["ai_trailer"], "{trailer}");
        }
        for ok in [
            "Co-authored-by: Jane Doe <jane@example.com>",
            "The generated mesh uses 64 cells",
            "Ran the AI-free baseline",
        ] {
            assert!(scan(ok, &deny).is_empty(), "{ok}");
        }
        assert!(DenyList::parse("(unclosed").is_err());
    }
}
