//! Checks for text about to be published. A hit names its rule, never the
//! matched text, so the term itself does not spread into records or logs.
use anyhow::{bail, Context, Result};
use regex::{Regex, RegexBuilder};
use std::sync::LazyLock;

/// Private terms that must never be published: one regular expression per
/// line, matched case-insensitively. Blank lines and `#` comments are skipped.
#[derive(Clone, Debug, Default)]
pub struct DenyList(Vec<(usize, Regex)>);
impl DenyList {
    pub fn parse(text: &str) -> Result<Self> {
        let mut rules = vec![];
        for (n, line) in text.lines().enumerate() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if line.len() > 512 || rules.len() >= 1000 {
                bail!(
                    "deny list line {} is too long or the list is too large",
                    n + 1
                );
            }
            let rule = RegexBuilder::new(line)
                .case_insensitive(true)
                .size_limit(1 << 20)
                .build()
                .with_context(|| format!("deny list line {} is not a valid pattern", n + 1))?;
            rules.push((n + 1, rule));
        }
        Ok(Self(rules))
    }
    pub fn len(&self) -> usize {
        self.0.len()
    }
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}
/// AI attribution trailers: a co-author line naming a model or vendor, or a
/// "generated with/by" line naming an AI tool.
static TRAILER: LazyLock<Regex> = LazyLock::new(|| {
    RegexBuilder::new(
        r"(?m)^\W*(co-authored-by:.*\b(claude|anthropic|openai|chatgpt|gpt-?\d|codex|copilot|gemini)\b|(\p{So}\s*)?generated (with|by) .*\b(claude|chatgpt|codex|copilot|gemini|ai)\b)",
    )
    .case_insensitive(true)
    .build()
    .unwrap()
});
/// The rule `text` breaks, if any: `deny_list:<line>` or `ai_trailer`.
pub fn scan(text: &str, deny: &DenyList) -> Option<String> {
    if let Some((line, _)) = deny.0.iter().find(|(_, rule)| rule.is_match(text)) {
        return Some(format!("deny_list:{line}"));
    }
    TRAILER.is_match(text).then(|| "ai_trailer".into())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn hits_name_the_rule_and_ordinary_text_passes() {
        let deny = DenyList::parse("# private names\n\nAlice Example\nproject-\\d+\n").unwrap();
        assert_eq!(deny.len(), 2);
        assert_eq!(
            scan("thanks, alice example", &deny).as_deref(),
            Some("deny_list:3")
        );
        assert_eq!(
            scan("see PROJECT-42", &deny).as_deref(),
            Some("deny_list:4")
        );
        for trailer in [
            "Fix it\n\nCo-Authored-By: Claude Opus <noreply@anthropic.com>",
            "Done.\n🤖 Generated with Claude Code",
            "Generated by ChatGPT",
        ] {
            assert_eq!(
                scan(trailer, &deny).as_deref(),
                Some("ai_trailer"),
                "{trailer}"
            );
        }
        for ok in [
            "Co-authored-by: Jane Doe <jane@example.com>",
            "The generated mesh uses 64 cells",
            "Ran the AI-free baseline",
        ] {
            assert_eq!(scan(ok, &deny), None, "{ok}");
        }
        assert!(DenyList::parse("(unclosed").is_err());
    }
}
