pub mod approvals;
pub mod attention;
pub mod cli;
pub mod config;
pub mod control;
pub use fridica_core as core;
pub mod daemon;
pub mod doctor;
pub mod exec;
pub mod github;
pub mod machines;
pub mod parent;
pub mod report;
pub mod slack;
pub mod store;
pub mod threads;
pub mod workers;
